-- ============================================================================
-- Functional tests for the Service role (after-sales loop), run as real
-- non-superuser users so RLS + the guard triggers actually apply.
-- Runs after 10_workflow_tests.sql and reuses the AZ-200 build it created.
-- ============================================================================
\set QUIET on
set client_min_messages = notice;

-- ── people ──────────────────────────────────────────────────────────────────
insert into auth.users (id, email) values
  ('50000000-0000-0000-0000-000000000001','service@az.co'),
  ('50000000-0000-0000-0000-000000000002','tech@az.co');

insert into profiles (id, full_name, email, role, status) values
  ('50000000-0000-0000-0000-000000000001','Kabir Service','service@az.co','service','active'),
  ('50000000-0000-0000-0000-000000000002','Arjun Tech','tech@az.co','workshop','active');

\echo ''
\echo '=== A build only enters service once it is delivered ==============='

set role authenticated;

-- the workflow tests offboarded the original PM, so give AZ-200 one again
set test.uid = 'a0000000-0000-0000-0000-000000000001';           -- admin
select public.fn_assign_pm('77777777-0000-0000-0000-000000000001',
                           'b0000000-0000-0000-0000-000000000002');

set test.uid = 'd0000000-0000-0000-0000-000000000001';           -- a welder
select t_expect_error(
  $$select public.fn_mark_delivered('77777777-0000-0000-0000-000000000001')$$,
  'only the build''s PM (or admin) can mark it delivered');

set test.uid = 'b0000000-0000-0000-0000-000000000002';           -- the PM
select t_expect_error(
  $$select public.fn_mark_delivered('77777777-0000-0000-0000-000000000001')$$,
  'delivery is refused while stages are still not approved');

select public.fn_mark_delivered('77777777-0000-0000-0000-000000000001', null, true);
select t_assert((select status from projects where code = 'AZ-200') = 'delivered',
                'F1 forcing delivery flips the build to delivered');
select t_assert((select actual_delivery_date from projects where code = 'AZ-200') = current_date,
                'actual_delivery_date is stamped (nothing used to set it)');
select t_expect_error(
  $$select public.fn_mark_delivered('77777777-0000-0000-0000-000000000001', null, true)$$,
  'a build cannot be delivered twice');

reset role; set test.uid = '';
select t_assert((select count(*) from notifications
                  where user_id = '50000000-0000-0000-0000-000000000001'
                    and type = 'delivered') = 1,
                'the service team is told a new truck is in service');
select t_assert((select count(*) from notifications
                  where user_id = 'f0000000-0000-0000-0000-000000000001'
                    and type = 'delivered') = 1,
                'the client is told their truck is delivered');
set role authenticated;

\echo ''
\echo '=== The client raises a request → service actually hears about it ==='

set test.uid = 'f0000000-0000-0000-0000-000000000001';           -- the client
insert into tickets (project_id, category, description, priority)
values ('77777777-0000-0000-0000-000000000001','equipment',
        'The TV will not power on since this morning.','high');

select t_assert((select ticket_number from tickets order by created_at desc limit 1) like 'T-%',
                'the ticket number is generated by the database, not the app');
select t_assert((select sla_due is not null from tickets order by created_at desc limit 1),
                'SLA deadline is set on insert (it was never set before)');
select t_assert((select sla_due <= now() + interval '4 hours' + interval '1 minute'
                   from tickets order by created_at desc limit 1),
                'a high-priority request gets the 4-hour SLA');
select t_assert((select raised_by from tickets order by created_at desc limit 1)
                = 'f0000000-0000-0000-0000-000000000001',
                'the raiser is recorded even when the app does not send it');

reset role; set test.uid = '';
select t_assert((select count(*) from notifications
                  where user_id = '50000000-0000-0000-0000-000000000001'
                    and type = 'ticket') = 1,
                'every service member is notified of a new client request');
set role authenticated;

set test.uid = 'f0000000-0000-0000-0000-000000000001';
select t_expect_error($$select public.fn_create_ticket(
    '77777777-0000-0000-0000-000000000001','other','phoned in','low')$$,
  'a client cannot raise a ticket "on behalf of" anyone');

set test.uid = '50000000-0000-0000-0000-000000000001';           -- service
select t_expect_error($$select public.fn_create_ticket(
    '77777777-0000-0000-0000-000000000001','other','  ','low')$$,
  'a ticket needs a description');
select t_assert(public.fn_create_ticket('77777777-0000-0000-0000-000000000001',
    'cosmetic','Client phoned: door handle is loose.','low') is not null,
  'service can raise a ticket on the client''s behalf');

\echo ''
\echo '=== Triage → assign → schedule a visit ============================'

set test.uid = '50000000-0000-0000-0000-000000000001';
select t_expect_error(format($$select public.fn_assign_ticket(%L,%L)$$,
    (select id from tickets where priority = 'high' order by created_at desc limit 1),
    'c0000000-0000-0000-0000-000000000001'),
  'a designer cannot be put on a service ticket');

select public.fn_assign_ticket(
  (select id from tickets where priority = 'high' order by created_at desc limit 1),
  '50000000-0000-0000-0000-000000000002');
select t_assert((select status from tickets where priority = 'high' order by created_at desc limit 1)
                = 'in_progress',
                'assigning a ticket moves it out of the open queue');

select public.fn_schedule_visit(
  (select id from tickets where priority = 'high' order by created_at desc limit 1),
  '50000000-0000-0000-0000-000000000002', now() + interval '1 day', 'Carry a spare panel.');
select t_assert((select count(*) from service_visits where status = 'scheduled') = 1,
                'the visit is booked (service_visits was never written before)');

-- re-scheduling must not leave two live bookings on one ticket
select public.fn_schedule_visit(
  (select id from tickets where priority = 'high' order by created_at desc limit 1),
  '50000000-0000-0000-0000-000000000002', now() + interval '2 days');
select t_assert((select count(*) from service_visits
                  where status = 'scheduled') = 1,
                're-scheduling replaces the open booking instead of duplicating it');

set test.uid = 'd0000000-0000-0000-0000-000000000001';           -- a welder
select t_expect_error(format($$select public.fn_schedule_visit(%L,%L,now())$$,
    (select id from tickets where priority = 'high' order by created_at desc limit 1),
    '50000000-0000-0000-0000-000000000002'),
  'only the service team can schedule a visit');

-- the client can see the visit booked for their own ticket
set test.uid = 'f0000000-0000-0000-0000-000000000001';
select t_assert((select count(*) from service_visits) >= 1,
                'the client can see the visit booked on their request');

\echo ''
\echo '=== Resolve → client is told → close =============================='

set test.uid = '50000000-0000-0000-0000-000000000001';
select t_expect_error(format($$select public.fn_resolve_ticket(%L,'repair',null)$$,
    (select id from tickets where priority = 'high' order by created_at desc limit 1)),
  'resolving requires a note — the client reads it');

select t_expect_error(format($$select public.fn_close_ticket(%L)$$,
    (select id from tickets where priority = 'high' order by created_at desc limit 1)),
  'a ticket cannot be closed before it is resolved');

select public.fn_resolve_ticket(
  (select id from tickets where priority = 'high' order by created_at desc limit 1),
  'warranty_replace', 'Replaced the TV under warranty, new serial logged.');

select t_assert((select status from tickets where priority = 'high' order by created_at desc limit 1)
                = 'resolved', 'the ticket is resolved');
select t_assert((select resolved_at is not null from tickets
                  where priority = 'high' order by created_at desc limit 1),
                'resolved_at is stamped');
select t_assert((select count(*) from service_visits where status = 'scheduled') = 0,
                'the booked visit is marked done, not left pending forever');

reset role; set test.uid = '';
select t_assert((select count(*) from notifications
                  where user_id = 'f0000000-0000-0000-0000-000000000001'
                    and type = 'resolved') = 1,
                'the client is told how their issue was resolved');
set role authenticated;

\echo ''
\echo '=== The client says it is still broken → reopen ===================='

set test.uid = 'f0000000-0000-0000-0000-000000000001';
select public.fn_reopen_ticket(
  (select id from tickets where resolution_type = 'warranty_replace' limit 1),
  'Still not working after the replacement.');
select t_assert((select status from tickets where resolution_type = 'warranty_replace' limit 1)
                = 'in_progress', 'reopening puts the ticket back in play');
select t_assert((select priority from tickets where resolution_type = 'warranty_replace' limit 1)
                = 'high', 'a reopened ticket jumps the queue');

reset role; set test.uid = '';
select t_assert((select count(*) from notifications
                  where user_id = '50000000-0000-0000-0000-000000000001'
                    and type = 'ticket') >= 2,
                'the service team is told about the reopen');
set role authenticated;

\echo ''
\echo '=== Warranty lookup ==============================================='

set test.uid = '50000000-0000-0000-0000-000000000001';           -- service
select t_assert((select count(*) from public.fn_warranty_search('SN-TEST')) = 1,
                'warranty lookup finds a part by serial');
select t_assert((select count(*) from public.fn_warranty_search('AZ-200')) >= 1,
                'warranty lookup finds parts by truck code');
select t_assert((select project_code from public.fn_warranty_search('SN-TEST-001')) = 'AZ-200',
                'the result carries the truck it is fitted to');

set test.uid = 'f0000000-0000-0000-0000-000000000001';           -- the client
select t_assert((select count(*) from public.fn_warranty_search('SN-TEST')) = 0,
                'a client cannot use the staff warranty lookup');

reset role;
\echo ''
\echo '=== SERVICE TESTS PASSED =========================================='
