-- ============================================================================
-- DEMO DATA — Notifications for the admin user (a8 screen testable now).
-- Real notifications will be generated by triggers/roles later; this just
-- fills the feed so you can see it. Safe to run once (idempotent guard).
-- Run in Supabase SQL editor.
-- ============================================================================
do $$
declare v_admin uuid;
begin
  select id into v_admin from profiles where role = 'admin' order by created_at asc limit 1;
  if v_admin is null then
    raise notice 'No admin profile found.';
    return;
  end if;
  if exists (select 1 from notifications where user_id = v_admin and title like 'Espresso machine%') then
    raise notice 'Notification demo already present — skipping.';
    return;
  end if;

  insert into notifications (user_id, type, title, body, read, created_at) values
    (v_admin, 'order_due',  'Espresso machine for AZ-118 must be ordered today', '45-day lead time', false, now() - interval '2 hours'),
    (v_admin, 'stage_done', 'Priya completed Exterior cladding on AZ-118',        null,               false, now() - interval '3 hours'),
    (v_admin, 'at_risk',    'AZ-104 moved to at-risk — electrical delayed',        null,               false, now() - interval '5 hours'),
    (v_admin, 'po',         'Rahul created a PO for kitchen equipment',            null,               true,  now() - interval '1 day'),
    (v_admin, 'approved',   'Client approved the design for AZ-118',               null,               true,  now() - interval '2 days');

  raise notice 'Notification demo inserted for admin %.', v_admin;
end $$;
